// Riwaayat Royale - Divided Catalog Data (100 Outfits Divided Into 8 Function Options)

const PRODUCTS_DATA = [
{
  id: 'rr-hald-1',
  name: 'Surya Organza Haldi Set 1',
  category: 'Indo-Western',
  occasion: ['Haldi', 'Party & Festive'],
  price: 32000,
  originalPrice: 39000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_135_0T3A6883_df8ca5db-2969-4c62-b3c7-61905d69d7ff_400x.jpg', 'assets/images/haldi/imgi_136_72a22b6c257b330afa44deb628364810.jpg', 'assets/images/haldi/imgi_137_e52c90c36ec7abc780a8d4b518886698.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 18
},
{
  id: 'rr-hald-2',
  name: '72A22b6c257b330afa44deb628364810',
  category: 'Lehenga',
  occasion: ['Haldi', 'Party & Festive'],
  price: 33800,
  originalPrice: 41000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_136_72a22b6c257b330afa44deb628364810.jpg', 'assets/images/haldi/imgi_137_e52c90c36ec7abc780a8d4b518886698.jpg', 'assets/images/haldi/imgi_139_L12.01.25_2496_db440ee9-a286-4ba1-8437-a39c92192f26_400x.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 19
},
{
  id: 'rr-hald-3',
  name: 'E52c90c36ec7abc780a8d4b518886698',
  category: 'Sharara',
  occasion: ['Haldi', 'Party & Festive'],
  price: 35600,
  originalPrice: 43000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_137_e52c90c36ec7abc780a8d4b518886698.jpg', 'assets/images/haldi/imgi_139_L12.01.25_2496_db440ee9-a286-4ba1-8437-a39c92192f26_400x.jpg', 'assets/images/haldi/imgi_140_yellow-organza-silk-embroidered-gorgeous-indowestern-skirt-set-iwsuscc48265562-u.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 20
},
{
  id: 'rr-hald-4',
  name: 'Surya Organza Haldi Set 4',
  category: 'Indo-Western',
  occasion: ['Haldi', 'Party & Festive'],
  price: 37400,
  originalPrice: 45000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_139_L12.01.25_2496_db440ee9-a286-4ba1-8437-a39c92192f26_400x.jpg', 'assets/images/haldi/imgi_140_yellow-organza-silk-embroidered-gorgeous-indowestern-skirt-set-iwsuscc48265562-u.jpg', 'assets/images/haldi/imgi_141_bd9267dbcbfc7088596ee22ce7a34294.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 21
},
{
  id: 'rr-hald-5',
  name: 'Surya Organza Haldi Set 5',
  category: 'Sharara',
  occasion: ['Haldi', 'Party & Festive'],
  price: 39200,
  originalPrice: 47000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_140_yellow-organza-silk-embroidered-gorgeous-indowestern-skirt-set-iwsuscc48265562-u.jpg', 'assets/images/haldi/imgi_141_bd9267dbcbfc7088596ee22ce7a34294.jpg', 'assets/images/haldi/imgi_144_Why Yellow and Mustard Shades Dominate Haldi Ceremony Fashion_D.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 22
},
{
  id: 'rr-hald-6',
  name: 'Bd9267dbcbfc7088596ee22ce7a34294',
  category: 'Lehenga',
  occasion: ['Haldi', 'Party & Festive'],
  price: 41000,
  originalPrice: 49000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_141_bd9267dbcbfc7088596ee22ce7a34294.jpg', 'assets/images/haldi/imgi_144_Why Yellow and Mustard Shades Dominate Haldi Ceremony Fashion_D.jpg', 'assets/images/haldi/imgi_145_Vibrant Haldi Lehengas to Brighten Up Your Pre-Wedding Ceremony_Blog 1.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 23
},
{
  id: 'rr-hald-7',
  name: 'Surya Organza Haldi Set 7',
  category: 'Indo-Western',
  occasion: ['Haldi', 'Party & Festive'],
  price: 42800,
  originalPrice: 51000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_144_Why Yellow and Mustard Shades Dominate Haldi Ceremony Fashion_D.jpg', 'assets/images/haldi/imgi_145_Vibrant Haldi Lehengas to Brighten Up Your Pre-Wedding Ceremony_Blog 1.jpg', 'assets/images/haldi/imgi_146_3cf2216c1930b4cb89f3173ff7fa47e4.png'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 24
},
{
  id: 'rr-hald-8',
  name: 'Surya Organza Haldi Set 8',
  category: 'Lehenga',
  occasion: ['Haldi', 'Party & Festive'],
  price: 44600,
  originalPrice: 53000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_145_Vibrant Haldi Lehengas to Brighten Up Your Pre-Wedding Ceremony_Blog 1.jpg', 'assets/images/haldi/imgi_146_3cf2216c1930b4cb89f3173ff7fa47e4.png', 'assets/images/haldi/imgi_148_g3blog-haldi-outfits-for-bride-bridesmaids-guests-trends-010ff9e70fb9.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 25
},
{
  id: 'rr-hald-9',
  name: '3Cf2216c1930b4cb89f3173ff7fa47e4',
  category: 'Sharara',
  occasion: ['Haldi', 'Party & Festive'],
  price: 46400,
  originalPrice: 55000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_146_3cf2216c1930b4cb89f3173ff7fa47e4.png', 'assets/images/haldi/imgi_148_g3blog-haldi-outfits-for-bride-bridesmaids-guests-trends-010ff9e70fb9.jpg', 'assets/images/haldi/imgi_149_L12.01.25_3256_400x.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 26
},
{
  id: 'rr-hald-10',
  name: 'Surya Organza Haldi Set 10',
  category: 'Indo-Western',
  occasion: ['Haldi', 'Party & Festive'],
  price: 48200,
  originalPrice: 57000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_148_g3blog-haldi-outfits-for-bride-bridesmaids-guests-trends-010ff9e70fb9.jpg', 'assets/images/haldi/imgi_149_L12.01.25_3256_400x.jpg', 'assets/images/haldi/imgi_151_mustard-yellow-dori-embroidered-organza-sharara-suit-for-haldi-lstv129697-1_2_1.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 27
},
{
  id: 'rr-hald-11',
  name: 'L12.01.25 3256 400X',
  category: 'Sharara',
  occasion: ['Haldi', 'Party & Festive'],
  price: 50000,
  originalPrice: 59000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_149_L12.01.25_3256_400x.jpg', 'assets/images/haldi/imgi_151_mustard-yellow-dori-embroidered-organza-sharara-suit-for-haldi-lstv129697-1_2_1.jpg', 'assets/images/haldi/imgi_152_52-7070491.png'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 28
},
{
  id: 'rr-hald-12',
  name: 'Surya Organza Haldi Set 12',
  category: 'Lehenga',
  occasion: ['Haldi', 'Party & Festive'],
  price: 51800,
  originalPrice: 61000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_151_mustard-yellow-dori-embroidered-organza-sharara-suit-for-haldi-lstv129697-1_2_1.jpg', 'assets/images/haldi/imgi_152_52-7070491.png', 'assets/images/haldi/imgi_154_644_964_220224tr40-1_1.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 29
},
{
  id: 'rr-hald-13',
  name: '52 7070491',
  category: 'Indo-Western',
  occasion: ['Haldi', 'Party & Festive'],
  price: 53600,
  originalPrice: 63000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_152_52-7070491.png', 'assets/images/haldi/imgi_154_644_964_220224tr40-1_1.jpg', 'assets/images/haldi/imgi_155_3e3371bc-78e6-4b64-bc2b-685254a96842_resource.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 30
},
{
  id: 'rr-hald-14',
  name: '644 964 220224Tr40 1 1',
  category: 'Lehenga',
  occasion: ['Haldi', 'Party & Festive'],
  price: 55400,
  originalPrice: 65000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_154_644_964_220224tr40-1_1.jpg', 'assets/images/haldi/imgi_155_3e3371bc-78e6-4b64-bc2b-685254a96842_resource.jpg', 'assets/images/haldi/imgi_156_screenshot_2024-12-27_at_4.08.56_pm.png'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 31
},
{
  id: 'rr-hald-15',
  name: '3E3371bc 78E6 4B64 Bc2b 685254A96842 Resource',
  category: 'Sharara',
  occasion: ['Haldi', 'Party & Festive'],
  price: 57200,
  originalPrice: 67000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_155_3e3371bc-78e6-4b64-bc2b-685254a96842_resource.jpg', 'assets/images/haldi/imgi_156_screenshot_2024-12-27_at_4.08.56_pm.png', 'assets/images/haldi/imgi_157_cream-beige-silk-palazzo-suit-with-beads-embroidered-lstv144513-1_1_3.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 32
},
{
  id: 'rr-hald-16',
  name: 'Screenshot 2024 12 27 At 4.08.56 Pm',
  category: 'Indo-Western',
  occasion: ['Haldi', 'Party & Festive'],
  price: 59000,
  originalPrice: 69000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_156_screenshot_2024-12-27_at_4.08.56_pm.png', 'assets/images/haldi/imgi_157_cream-beige-silk-palazzo-suit-with-beads-embroidered-lstv144513-1_1_3.jpg', 'assets/images/haldi/imgi_158_b874ba9e06123245fb4ce0b2616fc6d5.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 33
},
{
  id: 'rr-hald-17',
  name: 'Surya Organza Haldi Set 17',
  category: 'Sharara',
  occasion: ['Haldi', 'Party & Festive'],
  price: 60800,
  originalPrice: 71000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_157_cream-beige-silk-palazzo-suit-with-beads-embroidered-lstv144513-1_1_3.jpg', 'assets/images/haldi/imgi_158_b874ba9e06123245fb4ce0b2616fc6d5.jpg', 'assets/images/haldi/imgi_159_shruti-haldi-for-haldi-outfit-for-wedding-wholesale-collection-5-2023-06-06_13_33_29.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 34
},
{
  id: 'rr-hald-18',
  name: 'B874ba9e06123245fb4ce0b2616fc6d5',
  category: 'Lehenga',
  occasion: ['Haldi', 'Party & Festive'],
  price: 62600,
  originalPrice: 73000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_158_b874ba9e06123245fb4ce0b2616fc6d5.jpg', 'assets/images/haldi/imgi_159_shruti-haldi-for-haldi-outfit-for-wedding-wholesale-collection-5-2023-06-06_13_33_29.jpg', 'assets/images/haldi/imgi_161_51f63011042cb0b32d110abdc44a91c5.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 35
},
{
  id: 'rr-hald-19',
  name: 'Surya Organza Haldi Set 19',
  category: 'Indo-Western',
  occasion: ['Haldi', 'Party & Festive'],
  price: 64400,
  originalPrice: 75000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_159_shruti-haldi-for-haldi-outfit-for-wedding-wholesale-collection-5-2023-06-06_13_33_29.jpg', 'assets/images/haldi/imgi_161_51f63011042cb0b32d110abdc44a91c5.jpg', 'assets/images/haldi/imgi_162_yellow-faux-georgette-embroidered-sequins-breathtaking-lehenga--ghsepcb5127y-u.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 36
},
{
  id: 'rr-hald-20',
  name: '51F63011042cb0b32d110abdc44a91c5',
  category: 'Lehenga',
  occasion: ['Haldi', 'Party & Festive'],
  price: 66200,
  originalPrice: 77000,
  colors: ['Mustard Yellow', 'Sunshine Yellow'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/haldi/imgi_161_51f63011042cb0b32d110abdc44a91c5.jpg', 'assets/images/haldi/imgi_162_yellow-faux-georgette-embroidered-sequins-breathtaking-lehenga--ghsepcb5127y-u.jpg', 'assets/images/haldi/imgi_163_Horizontal-Blog-creatives-7-1.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Pure Organza Silk & Satin Chiffon',
  work: 'Hand Dori Embroidery, Gota Patti & Moti Work',
  description: 'Radiate warmth and joy in this bright yellow Haldi ensemble handcrafted with intricate dori embroidery.',
  rating: 4.9,
  reviewsCount: 37
},
{
  id: 'rr-sang-1',
  name: 'BHASIN63210',
  category: 'Lehenga',
  occasion: ['Mehendi', 'Sangeet'],
  price: 38000,
  originalPrice: 46000,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_100_BHASIN63210.jpg', 'assets/images/sangeet/imgi_102_690e698f03ec66b7f8431cdcfaab0417.jpg', 'assets/images/sangeet/imgi_103_9bc0435d-3b49-43cf-a527-388fcbad9507.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 24
},
{
  id: 'rr-sang-2',
  name: '690E698f03ec66b7f8431cdcfaab0417',
  category: 'Sharara',
  occasion: ['Sangeet', 'Party & Festive'],
  price: 40200,
  originalPrice: 48500,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_102_690e698f03ec66b7f8431cdcfaab0417.jpg', 'assets/images/sangeet/imgi_103_9bc0435d-3b49-43cf-a527-388fcbad9507.jpg', 'assets/images/sangeet/imgi_104_119738-seema-gujral.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 25
},
{
  id: 'rr-sang-3',
  name: '9Bc0435d 3B49 43Cf A527 388Fcbad9507',
  category: 'Designer Suit',
  occasion: ['Mehendi', 'Sangeet'],
  price: 42400,
  originalPrice: 51000,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_103_9bc0435d-3b49-43cf-a527-388fcbad9507.jpg', 'assets/images/sangeet/imgi_104_119738-seema-gujral.jpg', 'assets/images/sangeet/imgi_106_8-2.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 26
},
{
  id: 'rr-sang-4',
  name: '119738 Seema Gujral',
  category: 'Lehenga',
  occasion: ['Sangeet', 'Party & Festive'],
  price: 44600,
  originalPrice: 53500,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_104_119738-seema-gujral.jpg', 'assets/images/sangeet/imgi_106_8-2.jpg', 'assets/images/sangeet/imgi_108_1aef435f1e90b1e3667c646b4c473477.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 27
},
{
  id: 'rr-sang-5',
  name: 'Chandrika Royal Sangeet Outfit 5',
  category: 'Designer Suit',
  occasion: ['Mehendi', 'Sangeet'],
  price: 46800,
  originalPrice: 56000,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_106_8-2.jpg', 'assets/images/sangeet/imgi_108_1aef435f1e90b1e3667c646b4c473477.jpg', 'assets/images/sangeet/imgi_109_teal-green-chiffon-trouser-suit-with-zari-work-for-mehndi-lstv141798-1.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 28
},
{
  id: 'rr-sang-6',
  name: '1Aef435f1e90b1e3667c646b4c473477',
  category: 'Sharara',
  occasion: ['Sangeet', 'Party & Festive'],
  price: 49000,
  originalPrice: 58500,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_108_1aef435f1e90b1e3667c646b4c473477.jpg', 'assets/images/sangeet/imgi_109_teal-green-chiffon-trouser-suit-with-zari-work-for-mehndi-lstv141798-1.jpg', 'assets/images/sangeet/imgi_110_Outfit--_indianvirasat.._weddingoutfit_shararaset_explore_model_foryoupage.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 29
},
{
  id: 'rr-sang-7',
  name: 'Chandrika Royal Sangeet Outfit 7',
  category: 'Lehenga',
  occasion: ['Mehendi', 'Sangeet'],
  price: 51200,
  originalPrice: 61000,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_109_teal-green-chiffon-trouser-suit-with-zari-work-for-mehndi-lstv141798-1.jpg', 'assets/images/sangeet/imgi_110_Outfit--_indianvirasat.._weddingoutfit_shararaset_explore_model_foryoupage.jpg', 'assets/images/sangeet/imgi_112_4BzS_aM8G28YrooR8e97hrMDplnKV60jiNsPQ6VQrII7C8nf6ySlUmGO8jmz1XCh0gA761NTnStVoP3qZcXGxLithh0mMF2StipIGds9ymzTvjFgsxZHKcW0WSTrae9zY3AyZNPC.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 30
},
{
  id: 'rr-sang-8',
  name: 'Chandrika Royal Sangeet Outfit 8',
  category: 'Sharara',
  occasion: ['Sangeet', 'Party & Festive'],
  price: 53400,
  originalPrice: 63500,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_110_Outfit--_indianvirasat.._weddingoutfit_shararaset_explore_model_foryoupage.jpg', 'assets/images/sangeet/imgi_112_4BzS_aM8G28YrooR8e97hrMDplnKV60jiNsPQ6VQrII7C8nf6ySlUmGO8jmz1XCh0gA761NTnStVoP3qZcXGxLithh0mMF2StipIGds9ymzTvjFgsxZHKcW0WSTrae9zY3AyZNPC.jpg', 'assets/images/sangeet/imgi_113_00c02cf5864c35e63ab6634b3b063ece.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 31
},
{
  id: 'rr-sang-9',
  name: 'Chandrika Royal Sangeet Outfit 9',
  category: 'Designer Suit',
  occasion: ['Mehendi', 'Sangeet'],
  price: 55600,
  originalPrice: 66000,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_112_4BzS_aM8G28YrooR8e97hrMDplnKV60jiNsPQ6VQrII7C8nf6ySlUmGO8jmz1XCh0gA761NTnStVoP3qZcXGxLithh0mMF2StipIGds9ymzTvjFgsxZHKcW0WSTrae9zY3AyZNPC.jpg', 'assets/images/sangeet/imgi_113_00c02cf5864c35e63ab6634b3b063ece.jpg', 'assets/images/sangeet/imgi_114_Priyani-Abilash-Cheyenne-Mountain-Resort-04975-scaled.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 32
},
{
  id: 'rr-sang-10',
  name: '00C02cf5864c35e63ab6634b3b063ece',
  category: 'Lehenga',
  occasion: ['Sangeet', 'Party & Festive'],
  price: 57800,
  originalPrice: 68500,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_113_00c02cf5864c35e63ab6634b3b063ece.jpg', 'assets/images/sangeet/imgi_114_Priyani-Abilash-Cheyenne-Mountain-Resort-04975-scaled.jpg', 'assets/images/sangeet/imgi_115_ae894cc449210917b8ba7f2f815c46da.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 33
},
{
  id: 'rr-sang-11',
  name: 'Chandrika Royal Sangeet Outfit 11',
  category: 'Designer Suit',
  occasion: ['Mehendi', 'Sangeet'],
  price: 60000,
  originalPrice: 71000,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_114_Priyani-Abilash-Cheyenne-Mountain-Resort-04975-scaled.jpg', 'assets/images/sangeet/imgi_115_ae894cc449210917b8ba7f2f815c46da.jpg', 'assets/images/sangeet/imgi_116_listicle_1769508829695_1s8qi_600x600.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 34
},
{
  id: 'rr-sang-12',
  name: 'Ae894cc449210917b8ba7f2f815c46da',
  category: 'Sharara',
  occasion: ['Sangeet', 'Party & Festive'],
  price: 62200,
  originalPrice: 73500,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_115_ae894cc449210917b8ba7f2f815c46da.jpg', 'assets/images/sangeet/imgi_116_listicle_1769508829695_1s8qi_600x600.jpg', 'assets/images/sangeet/imgi_117_d037f5a5443c327450194e1b7afb2dac.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 35
},
{
  id: 'rr-sang-13',
  name: 'Listicle 1769508829695 1S8qi 600X600',
  category: 'Lehenga',
  occasion: ['Mehendi', 'Sangeet'],
  price: 64400,
  originalPrice: 76000,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_116_listicle_1769508829695_1s8qi_600x600.jpg', 'assets/images/sangeet/imgi_117_d037f5a5443c327450194e1b7afb2dac.jpg', 'assets/images/sangeet/imgi_118_AD10775-E609526_4.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 36
},
{
  id: 'rr-sang-14',
  name: 'D037f5a5443c327450194e1b7afb2dac',
  category: 'Sharara',
  occasion: ['Sangeet', 'Party & Festive'],
  price: 66600,
  originalPrice: 78500,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_117_d037f5a5443c327450194e1b7afb2dac.jpg', 'assets/images/sangeet/imgi_118_AD10775-E609526_4.jpg', 'assets/images/sangeet/imgi_119_644_964_301225mm4-1.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 37
},
{
  id: 'rr-sang-15',
  name: 'AD10775 E609526 4',
  category: 'Designer Suit',
  occasion: ['Mehendi', 'Sangeet'],
  price: 68800,
  originalPrice: 81000,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_118_AD10775-E609526_4.jpg', 'assets/images/sangeet/imgi_119_644_964_301225mm4-1.jpg', 'assets/images/sangeet/imgi_120_Banner-2026-07-17T154339.562.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 38
},
{
  id: 'rr-sang-16',
  name: '644 964 301225Mm4 1',
  category: 'Lehenga',
  occasion: ['Sangeet', 'Party & Festive'],
  price: 71000,
  originalPrice: 83500,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_119_644_964_301225mm4-1.jpg', 'assets/images/sangeet/imgi_120_Banner-2026-07-17T154339.562.jpg', 'assets/images/sangeet/imgi_121_mustard-yellow-dori-embroidered-organza-sharara-suit-for-haldi-lstv129697-1_2_1.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 39
},
{
  id: 'rr-sang-17',
  name: 'Banner 2026 07 17T154339.562',
  category: 'Designer Suit',
  occasion: ['Mehendi', 'Sangeet'],
  price: 73200,
  originalPrice: 86000,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_120_Banner-2026-07-17T154339.562.jpg', 'assets/images/sangeet/imgi_121_mustard-yellow-dori-embroidered-organza-sharara-suit-for-haldi-lstv129697-1_2_1.jpg', 'assets/images/sangeet/imgi_122_Soumya_Rijul_Sangeet_2422.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 40
},
{
  id: 'rr-sang-18',
  name: 'Chandrika Royal Sangeet Outfit 18',
  category: 'Sharara',
  occasion: ['Sangeet', 'Party & Festive'],
  price: 75400,
  originalPrice: 88500,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_121_mustard-yellow-dori-embroidered-organza-sharara-suit-for-haldi-lstv129697-1_2_1.jpg', 'assets/images/sangeet/imgi_122_Soumya_Rijul_Sangeet_2422.jpg', 'assets/images/sangeet/imgi_123_Ivory-Lehenga-For-Sangeet-Sandhya.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 41
},
{
  id: 'rr-sang-19',
  name: 'Soumya Rijul Sangeet 2422',
  category: 'Lehenga',
  occasion: ['Mehendi', 'Sangeet'],
  price: 77600,
  originalPrice: 91000,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_122_Soumya_Rijul_Sangeet_2422.jpg', 'assets/images/sangeet/imgi_123_Ivory-Lehenga-For-Sangeet-Sandhya.jpg', 'assets/images/sangeet/imgi_124_2de7cf66ac060ff03ccfb4f2532c2326.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 42
},
{
  id: 'rr-sang-20',
  name: 'Ivory Lehenga For Sangeet Sandhya',
  category: 'Sharara',
  occasion: ['Sangeet', 'Party & Festive'],
  price: 79800,
  originalPrice: 93500,
  colors: ['Royal Purple', 'Teal Green', 'Sunset Orange'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom Stitching'],
  images: ['assets/images/sangeet/imgi_123_Ivory-Lehenga-For-Sangeet-Sandhya.jpg', 'assets/images/sangeet/imgi_124_2de7cf66ac060ff03ccfb4f2532c2326.jpg', 'assets/images/sangeet/imgi_125_54185-new-indian-dresses-image-social-hub-xyz-.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Viscose Georgette & Crinkled Chiffon',
  work: 'Tone-on-Tone Metallic Sequin & Antique Zari',
  description: 'Designed for high-energy Sangeet & Mehendi festivities with sparkling sequins and rich movement.',
  rating: 4.9,
  reviewsCount: 43
},
{
  id: 'rr-wed-1',
  name: '9A7cf7971620374674e23243dae23883',
  category: 'Anarkali',
  occasion: ['Wedding', 'Reception'],
  price: 85000,
  originalPrice: 105000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_156_9a7cf7971620374674e23243dae23883.jpg', 'assets/images/wedding/imgi_157_76926df8dc396345ed57ffee6738451a.jpg', 'assets/images/wedding/imgi_158_Mohi_Bridal_Banner_3.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 40
},
{
  id: 'rr-wed-2',
  name: '76926Df8dc396345ed57ffee6738451a',
  category: 'Lehenga',
  occasion: ['Wedding', 'Reception'],
  price: 89500,
  originalPrice: 110000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_157_76926df8dc396345ed57ffee6738451a.jpg', 'assets/images/wedding/imgi_158_Mohi_Bridal_Banner_3.jpg', 'assets/images/wedding/imgi_159_010_1901-C.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 41
},
{
  id: 'rr-wed-3',
  name: 'Mohi Bridal Banner 3',
  category: 'Lehenga',
  occasion: ['Wedding', 'Reception'],
  price: 94000,
  originalPrice: 115000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_158_Mohi_Bridal_Banner_3.jpg', 'assets/images/wedding/imgi_159_010_1901-C.jpg', 'assets/images/wedding/imgi_160_shutterstock_1123557119.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 42
},
{
  id: 'rr-wed-4',
  name: '010 1901 C',
  category: 'Lehenga',
  occasion: ['Wedding', 'Reception'],
  price: 98500,
  originalPrice: 120000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_159_010_1901-C.jpg', 'assets/images/wedding/imgi_160_shutterstock_1123557119.jpg', 'assets/images/wedding/imgi_161_2461copy_425x600.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 43
},
{
  id: 'rr-wed-5',
  name: 'Shutterstock 1123557119',
  category: 'Anarkali',
  occasion: ['Wedding', 'Reception'],
  price: 103000,
  originalPrice: 125000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_160_shutterstock_1123557119.jpg', 'assets/images/wedding/imgi_161_2461copy_425x600.jpg', 'assets/images/wedding/imgi_162_bridal.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 44
},
{
  id: 'rr-wed-6',
  name: '2461Copy 425X600',
  category: 'Lehenga',
  occasion: ['Wedding', 'Reception'],
  price: 107500,
  originalPrice: 130000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_161_2461copy_425x600.jpg', 'assets/images/wedding/imgi_162_bridal.jpg', 'assets/images/wedding/imgi_163_123718-manishmalhotra05.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 45
},
{
  id: 'rr-wed-7',
  name: 'Bridal',
  category: 'Lehenga',
  occasion: ['Wedding', 'Reception'],
  price: 112000,
  originalPrice: 135000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_162_bridal.jpg', 'assets/images/wedding/imgi_163_123718-manishmalhotra05.jpg', 'assets/images/wedding/imgi_164_Celebrate-Love-in-Wedding-Dresses-for-Men-Women.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 46
},
{
  id: 'rr-wed-8',
  name: '123718 Manishmalhotra05',
  category: 'Lehenga',
  occasion: ['Wedding', 'Reception'],
  price: 116500,
  originalPrice: 140000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_163_123718-manishmalhotra05.jpg', 'assets/images/wedding/imgi_164_Celebrate-Love-in-Wedding-Dresses-for-Men-Women.jpg', 'assets/images/wedding/imgi_165_classic-rose-gold-tissue-with-moti-and-gota-embroidered-sequins-lehenga-ghspf6062rgo-u.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 47
},
{
  id: 'rr-wed-9',
  name: 'Rajkumari Royal Bridal Lehenga 9',
  category: 'Anarkali',
  occasion: ['Wedding', 'Reception'],
  price: 121000,
  originalPrice: 145000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_164_Celebrate-Love-in-Wedding-Dresses-for-Men-Women.jpg', 'assets/images/wedding/imgi_165_classic-rose-gold-tissue-with-moti-and-gota-embroidered-sequins-lehenga-ghspf6062rgo-u.jpg', 'assets/images/wedding/imgi_167_10_Sequin_Lehenga_Set_480x480.webp'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 48
},
{
  id: 'rr-wed-10',
  name: 'Rajkumari Royal Bridal Lehenga 10',
  category: 'Lehenga',
  occasion: ['Wedding', 'Reception'],
  price: 125500,
  originalPrice: 150000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_165_classic-rose-gold-tissue-with-moti-and-gota-embroidered-sequins-lehenga-ghspf6062rgo-u.jpg', 'assets/images/wedding/imgi_167_10_Sequin_Lehenga_Set_480x480.webp', 'assets/images/wedding/imgi_168_Chic-Blouse-N-Multicolor-Embroidered-Lehenga-Set-GHBS02408526-u.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 49
},
{
  id: 'rr-wed-11',
  name: '10 Sequin Lehenga Set 480X480',
  category: 'Lehenga',
  occasion: ['Wedding', 'Reception'],
  price: 130000,
  originalPrice: 155000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_167_10_Sequin_Lehenga_Set_480x480.webp', 'assets/images/wedding/imgi_168_Chic-Blouse-N-Multicolor-Embroidered-Lehenga-Set-GHBS02408526-u.jpg', 'assets/images/wedding/imgi_169_Indo_Western_Skirt_Set.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 50
},
{
  id: 'rr-wed-12',
  name: 'Rajkumari Royal Bridal Lehenga 12',
  category: 'Lehenga',
  occasion: ['Wedding', 'Reception'],
  price: 134500,
  originalPrice: 160000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_168_Chic-Blouse-N-Multicolor-Embroidered-Lehenga-Set-GHBS02408526-u.jpg', 'assets/images/wedding/imgi_169_Indo_Western_Skirt_Set.jpg', 'assets/images/wedding/imgi_170_Indian-Wedding-Trends-2025-4.webp'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 51
},
{
  id: 'rr-wed-13',
  name: 'Indo Western Skirt Set',
  category: 'Anarkali',
  occasion: ['Wedding', 'Reception'],
  price: 139000,
  originalPrice: 165000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_169_Indo_Western_Skirt_Set.jpg', 'assets/images/wedding/imgi_170_Indian-Wedding-Trends-2025-4.webp', 'assets/images/wedding/imgi_171_Wedding-dresses-everything-you-already-didn%E2%80%99t-know-about-them.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 52
},
{
  id: 'rr-wed-14',
  name: 'Indian Wedding Trends 2025 4',
  category: 'Lehenga',
  occasion: ['Wedding', 'Reception'],
  price: 143500,
  originalPrice: 170000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_170_Indian-Wedding-Trends-2025-4.webp', 'assets/images/wedding/imgi_171_Wedding-dresses-everything-you-already-didn%E2%80%99t-know-about-them.jpg', 'assets/images/wedding/imgi_172_9bc0435d-3b49-43cf-a527-388fcbad9507.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 53
},
{
  id: 'rr-wed-15',
  name: 'Rajkumari Royal Bridal Lehenga 15',
  category: 'Lehenga',
  occasion: ['Wedding', 'Reception'],
  price: 148000,
  originalPrice: 175000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_171_Wedding-dresses-everything-you-already-didn%E2%80%99t-know-about-them.jpg', 'assets/images/wedding/imgi_172_9bc0435d-3b49-43cf-a527-388fcbad9507.jpg', 'assets/images/wedding/imgi_174_women-clothes.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 54
},
{
  id: 'rr-wed-16',
  name: '9Bc0435d 3B49 43Cf A527 388Fcbad9507',
  category: 'Lehenga',
  occasion: ['Wedding', 'Reception'],
  price: 152500,
  originalPrice: 180000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_172_9bc0435d-3b49-43cf-a527-388fcbad9507.jpg', 'assets/images/wedding/imgi_174_women-clothes.jpg', 'assets/images/wedding/imgi_175_Minimalistic-Bride_24-06-22.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 55
},
{
  id: 'rr-wed-17',
  name: 'Women Clothes',
  category: 'Anarkali',
  occasion: ['Wedding', 'Reception'],
  price: 157000,
  originalPrice: 185000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_174_women-clothes.jpg', 'assets/images/wedding/imgi_175_Minimalistic-Bride_24-06-22.jpg', 'assets/images/wedding/imgi_176_Indian-Wedding-Trends-2025-1.webp'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 56
},
{
  id: 'rr-wed-18',
  name: 'Minimalistic Bride 24 06 22',
  category: 'Lehenga',
  occasion: ['Wedding', 'Reception'],
  price: 161500,
  originalPrice: 190000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_175_Minimalistic-Bride_24-06-22.jpg', 'assets/images/wedding/imgi_176_Indian-Wedding-Trends-2025-1.webp', 'assets/images/wedding/imgi_177_featured-iamge-2.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 57
},
{
  id: 'rr-wed-19',
  name: 'Indian Wedding Trends 2025 1',
  category: 'Lehenga',
  occasion: ['Wedding', 'Reception'],
  price: 166000,
  originalPrice: 195000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_176_Indian-Wedding-Trends-2025-1.webp', 'assets/images/wedding/imgi_177_featured-iamge-2.jpg', 'assets/images/wedding/imgi_178_indian-wedding-guest-outfit-ideas-2021..-1.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 58
},
{
  id: 'rr-wed-20',
  name: 'Featured Iamge 2',
  category: 'Lehenga',
  occasion: ['Wedding', 'Reception'],
  price: 170500,
  originalPrice: 200000,
  colors: ['Crimson Red', 'Ivory Off-White', 'Royal Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'Custom Stitching'],
  images: ['assets/images/wedding/imgi_177_featured-iamge-2.jpg', 'assets/images/wedding/imgi_178_indian-wedding-guest-outfit-ideas-2021..-1.jpg', 'assets/images/wedding/imgi_179_107170-wedding-dresses-for-girls-4.jpg'],
  isNew: false,
  isBestSeller: true,
  fabric: 'Heritage Raw Silk & Dupion Silk',
  work: 'Pure Gold Zardozi, Dabka & Stone Embellishments',
  description: 'The pinnacle of Indian bridal couture. Handcrafted over 350 hours with gold zari embroidery and dual veil.',
  rating: 5.0,
  reviewsCount: 59
},
{
  id: 'rr-rece-1',
  name: 'Weddingimage3',
  category: 'Wedding Gown',
  occasion: ['Reception', 'Anniversary', 'New Arrivals'],
  price: 49000,
  originalPrice: 60000,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_110_weddingimage3.jpg', 'assets/images/reception/imgi_111_76926df8dc396345ed57ffee6738451a.jpg', 'assets/images/reception/imgi_112_Indian-Wedding-Pink-Georgette-Embrodered-Sequins-Lehenga-Choli-GHSDECBSM40-u.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 30
},
{
  id: 'rr-rece-2',
  name: '76926Df8dc396345ed57ffee6738451a',
  category: 'Designer Suit',
  occasion: ['Anniversary', 'Party & Festive'],
  price: 52000,
  originalPrice: 63500,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_111_76926df8dc396345ed57ffee6738451a.jpg', 'assets/images/reception/imgi_112_Indian-Wedding-Pink-Georgette-Embrodered-Sequins-Lehenga-Choli-GHSDECBSM40-u.jpg', 'assets/images/reception/imgi_113_shutterstock_1123557119.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 31
},
{
  id: 'rr-rece-3',
  name: 'Gulbadan Rose Gold Tissue Lehenga 3',
  category: 'Lehenga',
  occasion: ['Reception', 'Anniversary', 'New Arrivals'],
  price: 55000,
  originalPrice: 67000,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_112_Indian-Wedding-Pink-Georgette-Embrodered-Sequins-Lehenga-Choli-GHSDECBSM40-u.jpg', 'assets/images/reception/imgi_113_shutterstock_1123557119.jpg', 'assets/images/reception/imgi_114_8e39cd04e53839852066da4bd5eaa445.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 32
},
{
  id: 'rr-rece-4',
  name: 'Shutterstock 1123557119',
  category: 'Wedding Gown',
  occasion: ['Anniversary', 'Party & Festive'],
  price: 58000,
  originalPrice: 70500,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_113_shutterstock_1123557119.jpg', 'assets/images/reception/imgi_114_8e39cd04e53839852066da4bd5eaa445.jpg', 'assets/images/reception/imgi_115_2461copy_425x600.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 33
},
{
  id: 'rr-rece-5',
  name: '8E39cd04e53839852066da4bd5eaa445',
  category: 'Lehenga',
  occasion: ['Reception', 'Anniversary', 'New Arrivals'],
  price: 61000,
  originalPrice: 74000,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_114_8e39cd04e53839852066da4bd5eaa445.jpg', 'assets/images/reception/imgi_115_2461copy_425x600.jpg', 'assets/images/reception/imgi_116_Modern-Bride-_24-06-22.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 34
},
{
  id: 'rr-rece-6',
  name: '2461Copy 425X600',
  category: 'Designer Suit',
  occasion: ['Anniversary', 'Party & Festive'],
  price: 64000,
  originalPrice: 77500,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_115_2461copy_425x600.jpg', 'assets/images/reception/imgi_116_Modern-Bride-_24-06-22.jpg', 'assets/images/reception/imgi_117_010_1901-C.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 35
},
{
  id: 'rr-rece-7',
  name: 'Modern Bride  24 06 22',
  category: 'Wedding Gown',
  occasion: ['Reception', 'Anniversary', 'New Arrivals'],
  price: 67000,
  originalPrice: 81000,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_116_Modern-Bride-_24-06-22.jpg', 'assets/images/reception/imgi_117_010_1901-C.jpg', 'assets/images/reception/imgi_118_9a7cf7971620374674e23243dae23883.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 36
},
{
  id: 'rr-rece-8',
  name: '010 1901 C',
  category: 'Designer Suit',
  occasion: ['Anniversary', 'Party & Festive'],
  price: 70000,
  originalPrice: 84500,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_117_010_1901-C.jpg', 'assets/images/reception/imgi_118_9a7cf7971620374674e23243dae23883.jpg', 'assets/images/reception/imgi_119_1731343849.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 37
},
{
  id: 'rr-rece-9',
  name: '9A7cf7971620374674e23243dae23883',
  category: 'Lehenga',
  occasion: ['Reception', 'Anniversary', 'New Arrivals'],
  price: 73000,
  originalPrice: 88000,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_118_9a7cf7971620374674e23243dae23883.jpg', 'assets/images/reception/imgi_119_1731343849.jpg', 'assets/images/reception/imgi_120_123732-officialfahadhussayn.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 38
},
{
  id: 'rr-rece-10',
  name: '1731343849',
  category: 'Wedding Gown',
  occasion: ['Anniversary', 'Party & Festive'],
  price: 76000,
  originalPrice: 91500,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_119_1731343849.jpg', 'assets/images/reception/imgi_120_123732-officialfahadhussayn.jpg', 'assets/images/reception/imgi_121_Indian-Wedding-Trends-2025-1.webp'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 39
},
{
  id: 'rr-rece-11',
  name: '123732 Officialfahadhussayn',
  category: 'Lehenga',
  occasion: ['Reception', 'Anniversary', 'New Arrivals'],
  price: 79000,
  originalPrice: 95000,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_120_123732-officialfahadhussayn.jpg', 'assets/images/reception/imgi_121_Indian-Wedding-Trends-2025-1.webp', 'assets/images/reception/imgi_122_107114-wedding-dresses-for-girls-1.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 40
},
{
  id: 'rr-rece-12',
  name: 'Indian Wedding Trends 2025 1',
  category: 'Designer Suit',
  occasion: ['Anniversary', 'Party & Festive'],
  price: 82000,
  originalPrice: 98500,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_121_Indian-Wedding-Trends-2025-1.webp', 'assets/images/reception/imgi_122_107114-wedding-dresses-for-girls-1.jpg', 'assets/images/reception/imgi_123_e18406e4b7f35cc353b3ea0a79b79f5b.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 41
},
{
  id: 'rr-rece-13',
  name: '107114 Wedding Dresses For Girls 1',
  category: 'Wedding Gown',
  occasion: ['Reception', 'Anniversary', 'New Arrivals'],
  price: 85000,
  originalPrice: 102000,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_122_107114-wedding-dresses-for-girls-1.jpg', 'assets/images/reception/imgi_123_e18406e4b7f35cc353b3ea0a79b79f5b.jpg', 'assets/images/reception/imgi_124_Engagement_24-06-22.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 42
},
{
  id: 'rr-rece-14',
  name: 'E18406e4b7f35cc353b3ea0a79b79f5b',
  category: 'Designer Suit',
  occasion: ['Anniversary', 'Party & Festive'],
  price: 88000,
  originalPrice: 105500,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_123_e18406e4b7f35cc353b3ea0a79b79f5b.jpg', 'assets/images/reception/imgi_124_Engagement_24-06-22.jpg', 'assets/images/reception/imgi_125_Celebrate-Love-in-Wedding-Dresses-for-Men-Women.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 43
},
{
  id: 'rr-rece-15',
  name: 'Engagement 24 06 22',
  category: 'Lehenga',
  occasion: ['Reception', 'Anniversary', 'New Arrivals'],
  price: 91000,
  originalPrice: 109000,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_124_Engagement_24-06-22.jpg', 'assets/images/reception/imgi_125_Celebrate-Love-in-Wedding-Dresses-for-Men-Women.jpg', 'assets/images/reception/imgi_126_Wedding-dresses-everything-you-already-didn%E2%80%99t-know-about-them.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 44
},
{
  id: 'rr-rece-16',
  name: 'Gulbadan Rose Gold Tissue Lehenga 16',
  category: 'Wedding Gown',
  occasion: ['Anniversary', 'Party & Festive'],
  price: 94000,
  originalPrice: 112500,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_125_Celebrate-Love-in-Wedding-Dresses-for-Men-Women.jpg', 'assets/images/reception/imgi_126_Wedding-dresses-everything-you-already-didn%E2%80%99t-know-about-them.jpg', 'assets/images/reception/imgi_127_9bc0435d-3b49-43cf-a527-388fcbad9507.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 45
},
{
  id: 'rr-rece-17',
  name: 'Gulbadan Rose Gold Tissue Lehenga 17',
  category: 'Lehenga',
  occasion: ['Reception', 'Anniversary', 'New Arrivals'],
  price: 97000,
  originalPrice: 116000,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_126_Wedding-dresses-everything-you-already-didn%E2%80%99t-know-about-them.jpg', 'assets/images/reception/imgi_127_9bc0435d-3b49-43cf-a527-388fcbad9507.jpg', 'assets/images/reception/imgi_128_1146C.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 46
},
{
  id: 'rr-rece-18',
  name: '9Bc0435d 3B49 43Cf A527 388Fcbad9507',
  category: 'Designer Suit',
  occasion: ['Anniversary', 'Party & Festive'],
  price: 100000,
  originalPrice: 119500,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_127_9bc0435d-3b49-43cf-a527-388fcbad9507.jpg', 'assets/images/reception/imgi_128_1146C.jpg', 'assets/images/reception/imgi_129_shutterstock_1113360239.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 47
},
{
  id: 'rr-rece-19',
  name: '1146C',
  category: 'Wedding Gown',
  occasion: ['Reception', 'Anniversary', 'New Arrivals'],
  price: 103000,
  originalPrice: 123000,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_128_1146C.jpg', 'assets/images/reception/imgi_129_shutterstock_1113360239.jpg', 'assets/images/reception/imgi_130_g3blog-new-indian-wedding-dresses-trends-lehengas-suits-sarees-ac22647efb69.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 48
},
{
  id: 'rr-rece-20',
  name: 'Shutterstock 1113360239',
  category: 'Designer Suit',
  occasion: ['Anniversary', 'Party & Festive'],
  price: 106000,
  originalPrice: 126500,
  colors: ['Rose Gold', 'Peach Pink', 'Wine Red'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/reception/imgi_129_shutterstock_1113360239.jpg', 'assets/images/reception/imgi_130_g3blog-new-indian-wedding-dresses-trends-lehengas-suits-sarees-ac22647efb69.jpg', 'assets/images/reception/imgi_131_123748-ejaaz-couture.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Luminous Tissue Silk & Velvet',
  work: 'Moti, Gota Patti & Crystal Dust Highlights',
  description: 'Tailored for grand evening receptions and milestone anniversary galas with metallic lustres.',
  rating: 4.9,
  reviewsCount: 49
},
{
  id: 'rr-part-1',
  name: '010 1901 C',
  category: 'Indo-Western',
  occasion: ['Party & Festive', 'Engagement'],
  price: 35000,
  originalPrice: 42000,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_142_010_1901-C.jpg', 'assets/images/festive/imgi_143_Chic-Blouse-N-Multicolor-Embroidered-Lehenga-Set-GHBS02408526-u.jpg', 'assets/images/festive/imgi_144_1731343849.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 22
},
{
  id: 'rr-part-2',
  name: 'Ananya Royal Indo-Western Set 2',
  category: 'Anarkali',
  occasion: ['Party & Festive', 'Engagement'],
  price: 37000,
  originalPrice: 44400,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_143_Chic-Blouse-N-Multicolor-Embroidered-Lehenga-Set-GHBS02408526-u.jpg', 'assets/images/festive/imgi_144_1731343849.jpg', 'assets/images/festive/imgi_145_peach-silk-reception-lehenga-with-sweet-heart-neck-blouse-gg1586.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 23
},
{
  id: 'rr-part-3',
  name: '1731343849',
  category: 'Sharara',
  occasion: ['Party & Festive', 'Engagement'],
  price: 39000,
  originalPrice: 46800,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_144_1731343849.jpg', 'assets/images/festive/imgi_145_peach-silk-reception-lehenga-with-sweet-heart-neck-blouse-gg1586.jpg', 'assets/images/festive/imgi_147_2461copy_425x600.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 24
},
{
  id: 'rr-part-4',
  name: 'Ananya Royal Indo-Western Set 4',
  category: 'Indo-Western',
  occasion: ['Party & Festive', 'Engagement'],
  price: 41000,
  originalPrice: 49200,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_145_peach-silk-reception-lehenga-with-sweet-heart-neck-blouse-gg1586.jpg', 'assets/images/festive/imgi_147_2461copy_425x600.jpg', 'assets/images/festive/imgi_148_shutterstock_1123557119.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 25
},
{
  id: 'rr-part-5',
  name: '2461Copy 425X600',
  category: 'Sharara',
  occasion: ['Party & Festive', 'Engagement'],
  price: 43000,
  originalPrice: 51600,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_147_2461copy_425x600.jpg', 'assets/images/festive/imgi_148_shutterstock_1123557119.jpg', 'assets/images/festive/imgi_149_123718-manishmalhotra05.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 26
},
{
  id: 'rr-part-6',
  name: 'Shutterstock 1123557119',
  category: 'Anarkali',
  occasion: ['Party & Festive', 'Engagement'],
  price: 45000,
  originalPrice: 54000,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_148_shutterstock_1123557119.jpg', 'assets/images/festive/imgi_149_123718-manishmalhotra05.jpg', 'assets/images/festive/imgi_150_76168bdf20494934aefd805de914ab97.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 27
},
{
  id: 'rr-part-7',
  name: '123718 Manishmalhotra05',
  category: 'Indo-Western',
  occasion: ['Party & Festive', 'Engagement'],
  price: 47000,
  originalPrice: 56400,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_149_123718-manishmalhotra05.jpg', 'assets/images/festive/imgi_150_76168bdf20494934aefd805de914ab97.jpg', 'assets/images/festive/imgi_151_BB_216433_Final_320eb394-2ae4-42e1-91f1-7e342fc976df.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 28
},
{
  id: 'rr-part-8',
  name: '76168Bdf20494934aefd805de914ab97',
  category: 'Anarkali',
  occasion: ['Party & Festive', 'Engagement'],
  price: 49000,
  originalPrice: 58800,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_150_76168bdf20494934aefd805de914ab97.jpg', 'assets/images/festive/imgi_151_BB_216433_Final_320eb394-2ae4-42e1-91f1-7e342fc976df.jpg', 'assets/images/festive/imgi_152_featured-iamge-2.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 29
},
{
  id: 'rr-part-9',
  name: 'Ananya Royal Indo-Western Set 9',
  category: 'Sharara',
  occasion: ['Party & Festive', 'Engagement'],
  price: 51000,
  originalPrice: 61200,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_151_BB_216433_Final_320eb394-2ae4-42e1-91f1-7e342fc976df.jpg', 'assets/images/festive/imgi_152_featured-iamge-2.jpg', 'assets/images/festive/imgi_153_Indian-Wedding-Trends-2025-1.webp'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 30
},
{
  id: 'rr-part-10',
  name: 'Featured Iamge 2',
  category: 'Indo-Western',
  occasion: ['Party & Festive', 'Engagement'],
  price: 53000,
  originalPrice: 63600,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_152_featured-iamge-2.jpg', 'assets/images/festive/imgi_153_Indian-Wedding-Trends-2025-1.webp', 'assets/images/festive/imgi_154_76926df8dc396345ed57ffee6738451a.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 31
},
{
  id: 'rr-part-11',
  name: 'Indian Wedding Trends 2025 1',
  category: 'Sharara',
  occasion: ['Party & Festive', 'Engagement'],
  price: 55000,
  originalPrice: 66000,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_153_Indian-Wedding-Trends-2025-1.webp', 'assets/images/festive/imgi_154_76926df8dc396345ed57ffee6738451a.jpg', 'assets/images/festive/imgi_156_DSC_0418.webp'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 32
},
{
  id: 'rr-part-12',
  name: '76926Df8dc396345ed57ffee6738451a',
  category: 'Anarkali',
  occasion: ['Party & Festive', 'Engagement'],
  price: 57000,
  originalPrice: 68400,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_154_76926df8dc396345ed57ffee6738451a.jpg', 'assets/images/festive/imgi_156_DSC_0418.webp', 'assets/images/festive/imgi_157_79479-indian-bridal-wear-tarun-tahiliani-peach-anarkali-suit.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 33
},
{
  id: 'rr-part-13',
  name: 'DSC 0418',
  category: 'Indo-Western',
  occasion: ['Party & Festive', 'Engagement'],
  price: 59000,
  originalPrice: 70800,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_156_DSC_0418.webp', 'assets/images/festive/imgi_157_79479-indian-bridal-wear-tarun-tahiliani-peach-anarkali-suit.jpg', 'assets/images/festive/imgi_158_classic-rose-gold-tissue-with-moti-and-gota-embroidered-sequins-lehenga-ghspf6062rgo-u.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 34
},
{
  id: 'rr-part-14',
  name: 'Ananya Royal Indo-Western Set 14',
  category: 'Anarkali',
  occasion: ['Party & Festive', 'Engagement'],
  price: 61000,
  originalPrice: 73200,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_157_79479-indian-bridal-wear-tarun-tahiliani-peach-anarkali-suit.jpg', 'assets/images/festive/imgi_158_classic-rose-gold-tissue-with-moti-and-gota-embroidered-sequins-lehenga-ghspf6062rgo-u.jpg', 'assets/images/festive/imgi_159_123705-kalki-fashion.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 35
},
{
  id: 'rr-part-15',
  name: 'Ananya Royal Indo-Western Set 15',
  category: 'Sharara',
  occasion: ['Party & Festive', 'Engagement'],
  price: 63000,
  originalPrice: 75600,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_158_classic-rose-gold-tissue-with-moti-and-gota-embroidered-sequins-lehenga-ghspf6062rgo-u.jpg', 'assets/images/festive/imgi_159_123705-kalki-fashion.jpg', 'assets/images/festive/imgi_161_Celebrate-Love-in-Wedding-Dresses-for-Men-Women.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 36
},
{
  id: 'rr-part-16',
  name: '123705 Kalki Fashion',
  category: 'Indo-Western',
  occasion: ['Party & Festive', 'Engagement'],
  price: 65000,
  originalPrice: 78000,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_159_123705-kalki-fashion.jpg', 'assets/images/festive/imgi_161_Celebrate-Love-in-Wedding-Dresses-for-Men-Women.jpg', 'assets/images/festive/imgi_162_best-wedding-dresses-for-indian-bride1.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 37
},
{
  id: 'rr-part-17',
  name: 'Ananya Royal Indo-Western Set 17',
  category: 'Sharara',
  occasion: ['Party & Festive', 'Engagement'],
  price: 67000,
  originalPrice: 80400,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_161_Celebrate-Love-in-Wedding-Dresses-for-Men-Women.jpg', 'assets/images/festive/imgi_162_best-wedding-dresses-for-indian-bride1.jpg', 'assets/images/festive/imgi_163_indian-wedding-guest-outfit-ideas-2021..-1.jpg'],
  isNew: true,
  isBestSeller: true,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 38
},
{
  id: 'rr-part-18',
  name: 'Best Wedding Dresses For Indian Bride1',
  category: 'Anarkali',
  occasion: ['Party & Festive', 'Engagement'],
  price: 69000,
  originalPrice: 82800,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_162_best-wedding-dresses-for-indian-bride1.jpg', 'assets/images/festive/imgi_163_indian-wedding-guest-outfit-ideas-2021..-1.jpg', 'assets/images/festive/imgi_164_How_to_dress_for_Indian_wedding.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 39
},
{
  id: 'rr-part-19',
  name: 'Indian Wedding Guest Outfit Ideas 2021.. 1',
  category: 'Indo-Western',
  occasion: ['Party & Festive', 'Engagement'],
  price: 71000,
  originalPrice: 85200,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_163_indian-wedding-guest-outfit-ideas-2021..-1.jpg', 'assets/images/festive/imgi_164_How_to_dress_for_Indian_wedding.jpg', 'assets/images/festive/imgi_165_9a7cf7971620374674e23243dae23883.jpg'],
  isNew: true,
  isBestSeller: false,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 40
},
{
  id: 'rr-part-20',
  name: 'How To Dress For Indian Wedding',
  category: 'Anarkali',
  occasion: ['Party & Festive', 'Engagement'],
  price: 73000,
  originalPrice: 87600,
  colors: ['Burnt Orange', 'Pristine White', 'Mint Blue'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  images: ['assets/images/festive/imgi_164_How_to_dress_for_Indian_wedding.jpg', 'assets/images/festive/imgi_165_9a7cf7971620374674e23243dae23883.jpg', 'assets/images/festive/imgi_166_Mohi_Bridal_Banner_3.jpg'],
  isNew: false,
  isBestSeller: false,
  fabric: 'Faux Georgette & Mulmul Lining',
  work: 'Chikankari, Mirror Work & Cutdana',
  description: 'Statement festive wear engineered with modern silhouettes and traditional handcrafted details.',
  rating: 4.8,
  reviewsCount: 41
}
];

// Occasion Collections Metadata
const OCCASIONS_DATA = [
  {
    key: "Haldi",
    title: "Haldi",
    icon: "🌸",
    url: "haldi.html",
    tagline: "Sunshine, laughter & traditions.",
    description: "Discover bright mustard, golden yellow, and ivory organza outfits handcrafted for auspicious morning rituals.",
    image: "assets/images/haldi/imgi_140_yellow-organza-silk-embroidered-gorgeous-indowestern-skirt-set-iwsuscc48265562-u.jpg",
    accentColor: "#F59E0B"
  },
  {
    key: "Mehendi",
    title: "Mehendi",
    icon: "🌿",
    url: "mehendi.html",
    tagline: "Colour your celebration.",
    description: "Vibrant teal greens, lime silks, and playful shararas tailored for henna afternoon festivities.",
    image: "assets/images/sangeet/imgi_109_teal-green-chiffon-trouser-suit-with-zari-work-for-mehndi-lstv141798-1.jpg",
    accentColor: "#10B981"
  },
  {
    key: "Sangeet",
    title: "Sangeet",
    icon: "🎶",
    url: "sangeet.html",
    tagline: "Made for unforgettable nights.",
    description: "Dazzling sequined lehengas, shimmering gowns, and one-shoulder silhouettes built for music and dance.",
    image: "assets/images/sangeet/imgi_131_purple-georgette-embroidered-sequins-lehenga-ghsads271-u.jpg",
    accentColor: "#8B5CF6"
  },
  {
    key: "Wedding",
    title: "Wedding",
    icon: "👰",
    url: "wedding.html",
    tagline: "Your most beautiful beginning.",
    description: "Royal crimson raw silk lehengas, Kashmir pearl handloom, and magnificent gold zari bridal couture.",
    image: "assets/images/wedding/imgi_180_golden-grace-in-red-silk-zari-embroidered-stone-sequins-lehenga-ghsli2574150-u.jpg",
    accentColor: "#DC2626"
  },
  {
    key: "Reception",
    title: "Reception",
    icon: "💍",
    url: "reception.html",
    tagline: "Make your grand entrance.",
    description: "Rose gold tissue lehengas, jewel-toned violet gowns, and opulent metallic ensembles.",
    image: "assets/images/reception/imgi_189_classic-rose-gold-tissue-with-moti-and-gota-embroidered-sequins-lehenga-ghspf6062rgo-u.jpg",
    accentColor: "#EC4899"
  },
  {
    key: "Anniversary",
    title: "Anniversary",
    icon: "❤️",
    url: "anniversary.html",
    tagline: "Timeless romance renewed.",
    description: "Regal wine front-slit palazzo tunics and elegant couture pieces for milestone celebrations.",
    image: "assets/images/reception/imgi_159_wine-embroidered-front-slit-palazzo-outfit-palkhi-fashion-6215482.jpg",
    accentColor: "#991B1B"
  },
  {
    key: "Party & Festive",
    title: "Party & Festive",
    icon: "✨",
    url: "festive.html",
    tagline: "Glimmer in royal elegance.",
    description: "Fusion Indo-Western crop sets, modern Anarkalis, and statement party silhouettes.",
    image: "assets/images/reception/imgi_165_indowestern-sets-for-women-in-purple-georgette-embroidered-sequins-iwsuscc47757096-u.jpg",
    accentColor: "#F43F5E"
  }
];

// Royal Lookbook Gallery Images
const LOOKBOOK_IMAGES = [
  { src: "assets/images/wedding/imgi_180_golden-grace-in-red-silk-zari-embroidered-stone-sequins-lehenga-ghsli2574150-u.jpg", title: "Rajputana Crimson Bridal", tag: "Wedding Couture" },
  { src: "assets/images/reception/imgi_145_off-white-dupion-silk-lehenga-with-pearl-hand-embroidery-for-wedding-wear-llcv125036-1_1.jpg", title: "Noor Kashmir Pearl", tag: "Ivory Perfection" },
  { src: "assets/images/haldi/imgi_140_yellow-organza-silk-embroidered-gorgeous-indowestern-skirt-set-iwsuscc48265562-u.jpg", title: "Surya Kanti Organza", tag: "Haldi Rituals" },
  { src: "assets/images/sangeet/imgi_131_purple-georgette-embroidered-sequins-lehenga-ghsads271-u.jpg", title: "Chandrika Purple Sequin", tag: "Sangeet Gala" },
  { src: "assets/images/reception/imgi_189_classic-rose-gold-tissue-with-moti-and-gota-embroidered-sequins-lehenga-ghspf6062rgo-u.jpg", title: "Gulbadan Rose Gold", tag: "Reception Grandeur" },
  { src: "assets/images/reception/imgi_159_wine-embroidered-front-slit-palazzo-outfit-palkhi-fashion-6215482.jpg", title: "Devyani Velvet Slit", tag: "Anniversary Edition" }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PRODUCTS_DATA, OCCASIONS_DATA, LOOKBOOK_IMAGES };
}
